openapi: 3.0.3
info:
    title: Chatter service describing the streaming features of goa v2.
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for chatter
paths:
    /echoer:
        get:
            tags:
                - chatter
            summary: echoer chatter
            description: Echoes the message sent by the client.
            operationId: chatter#echoer
            responses:
                "101":
                    description: Switching Protocols response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Molestiae qui dicta.
                            example: Molestiae iure assumenda.
                "401":
                    description: 'unauthorized: Unauthorized response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Modi consequatur vero quas aliquam laudantium.
                            example: Voluptas dolor.
                "403":
                    description: 'invalid-scopes: Forbidden response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Consequatur corrupti possimus aliquid.
                            example: Doloremque quo neque rerum.
            security:
                - jwt_header_Authorization:
                    - stream:write
    /history:
        get:
            tags:
                - chatter
            summary: history chatter
            description: Returns the chat messages sent to the server.
            operationId: chatter#history
            parameters:
                - name: view
                  in: query
                  description: View to use to render the result
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: View to use to render the result
                    example: Velit voluptates enim quo vel modi.
                  example: Neque non eum mollitia qui est.
            responses:
                "101":
                    description: Switching Protocols response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ChatSummary'
                            example:
                                length: 357417275009774116
                                message: Nostrum minima voluptatum sequi.
                                sent_at: "2014-11-21T18:11:53Z"
                "401":
                    description: 'unauthorized: Unauthorized response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Beatae provident dolorum est.
                            example: Corporis nisi praesentium eaque.
                "403":
                    description: 'invalid-scopes: Forbidden response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Enim aliquid sunt suscipit quam ducimus.
                            example: Illum possimus voluptatem omnis consequatur amet.
            security:
                - jwt_header_Authorization:
                    - stream:read
    /listener:
        get:
            tags:
                - chatter
            summary: listener chatter
            description: Listens to the messages sent by the client.
            operationId: chatter#listener
            responses:
                "101":
                    description: Switching Protocols response.
                "401":
                    description: 'unauthorized: Unauthorized response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Quaerat qui.
                            example: Reprehenderit autem necessitatibus esse unde adipisci.
                "403":
                    description: 'invalid-scopes: Forbidden response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Expedita eos veniam illum.
                            example: Quis modi.
            security:
                - jwt_header_Authorization:
                    - stream:write
    /login:
        post:
            tags:
                - chatter
            summary: login chatter
            description: Creates a valid JWT token for auth to chat.
            operationId: chatter#login
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                description: New JWT token
                                example: Velit dolorum consequuntur culpa adipisci error.
                            example: Qui veritatis ea suscipit.
                "401":
                    description: 'unauthorized: Unauthorized response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Sunt modi aut accusamus atque blanditiis ad.
                            example: Voluptas quia eligendi et eaque.
            security:
                - basic_header_Authorization: []
    /subscribe:
        get:
            tags:
                - chatter
            summary: subscribe chatter
            description: Subscribe to events sent when new chat messages are added.
            operationId: chatter#subscribe
            responses:
                "101":
                    description: Switching Protocols response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Event'
                            example:
                                action: added
                                added_at: "1972-05-14T15:38:57Z"
                                details:
                                    Type: package_created
                                    Value: '{"id":4134264707864151039,"item":{"description":"Natus rerum eos at et rerum non."}}'
                                message: Et soluta deserunt sed et eum voluptatem.
                "401":
                    description: 'unauthorized: Unauthorized response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Temporibus possimus.
                            example: Suscipit corrupti deserunt.
                "403":
                    description: 'invalid-scopes: Forbidden response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Hic perspiciatis.
                            example: Consequuntur cumque id aliquam aliquam.
            security:
                - jwt_header_Authorization:
                    - stream:write
    /summary:
        get:
            tags:
                - chatter
            summary: summary chatter
            description: Summarizes the chat messages sent by the client.
            operationId: chatter#summary
            responses:
                "101":
                    description: Switching Protocols response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ChatSummaryResponseCollection'
                            example:
                                - length: 1434954528860155933
                                  message: Rerum ut excepturi quasi sit quas.
                                  sent_at: "1999-09-28T05:07:04Z"
                                - length: 1434954528860155933
                                  message: Rerum ut excepturi quasi sit quas.
                                  sent_at: "1999-09-28T05:07:04Z"
                "401":
                    description: 'unauthorized: Unauthorized response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: A voluptatem sunt iste.
                            example: Itaque tempore earum quae fugiat enim.
                "403":
                    description: 'invalid-scopes: Forbidden response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Quo consequuntur labore id porro corrupti.
                            example: Et architecto est numquam commodi rerum est.
            security:
                - jwt_header_Authorization:
                    - stream:write
components:
    schemas:
        ChatSummary:
            type: object
            properties:
                length:
                    type: integer
                    description: Length of the message sent
                    example: 2430958467436173643
                    format: int64
                message:
                    type: string
                    description: Message sent to the server
                    example: Quasi ipsa cupiditate itaque reprehenderit et.
                sent_at:
                    type: string
                    description: Time at which the message was sent
                    example: "1979-10-04T15:05:54Z"
                    format: date-time
            example:
                length: 8204346970065492253
                message: Nostrum ullam.
                sent_at: "1977-06-02T01:52:49Z"
            required:
                - message
                - sent_at
        ChatSummaryResponse:
            type: object
            properties:
                length:
                    type: integer
                    description: Length of the message sent
                    example: 2648962310168505400
                    format: int64
                message:
                    type: string
                    description: Message sent to the server
                    example: Veniam ducimus architecto culpa distinctio eum.
                sent_at:
                    type: string
                    description: Time at which the message was sent
                    example: "2005-07-25T18:13:54Z"
                    format: date-time
            description: ChatSummaryResponse result type (default view)
            example:
                length: 164363014785514393
                message: Consectetur commodi nihil autem in.
                sent_at: "1982-09-21T19:30:08Z"
            required:
                - message
                - sent_at
        ChatSummaryResponseCollection:
            type: array
            items:
                $ref: '#/components/schemas/ChatSummaryResponse'
            description: SummaryResponseBody is the result type for an array of ChatSummaryResponse (default view)
            example:
                - length: 1434954528860155933
                  message: Rerum ut excepturi quasi sit quas.
                  sent_at: "1999-09-28T05:07:04Z"
                - length: 1434954528860155933
                  message: Rerum ut excepturi quasi sit quas.
                  sent_at: "1999-09-28T05:07:04Z"
                - length: 1434954528860155933
                  message: Rerum ut excepturi quasi sit quas.
                  sent_at: "1999-09-28T05:07:04Z"
                - length: 1434954528860155933
                  message: Rerum ut excepturi quasi sit quas.
                  sent_at: "1999-09-28T05:07:04Z"
        Event:
            type: object
            properties:
                action:
                    type: string
                    example: added
                    enum:
                        - added
                added_at:
                    type: string
                    description: Time at which the message was added
                    example: "2000-05-29T06:28:02Z"
                    format: date-time
                details:
                    type: object
                    properties:
                        Type:
                            type: string
                            description: |-
                                Union type name, one of:
                                - "package_created"
                                - "package_deleted"
                                - "package_updated"
                            example: package_created
                            enum:
                                - package_created
                                - package_deleted
                                - package_updated
                        Value:
                            type: string
                            description: JSON encoded union value
                            example: '{"id":4134264707864151039,"item":{"description":"Natus rerum eos at et rerum non."}}'
                    example:
                        Type: package_created
                        Value: '{"id":4134264707864151039,"item":{"description":"Natus rerum eos at et rerum non."}}'
                    required:
                        - Type
                        - Value
                message:
                    type: string
                    description: Message sent to the server
                    example: Sequi nemo.
            example:
                action: added
                added_at: "2007-08-29T03:39:51Z"
                details:
                    Type: package_created
                    Value: '{"id":4134264707864151039,"item":{"description":"Natus rerum eos at et rerum non."}}'
                message: Sint esse non explicabo vero.
            required:
                - message
                - action
                - added_at
        Item:
            type: object
            properties:
                description:
                    type: string
                    example: Voluptatem vitae error eveniet dolores.
            example:
                description: Nostrum amet voluptatem corrupti.
        PackageCreatedEvent:
            type: object
            properties:
                id:
                    type: integer
                    description: Identifier of package
                    example: 7469039031279743034
                    format: int64
                item:
                    $ref: '#/components/schemas/Item'
            example:
                id: 5604667108238848724
                item:
                    description: Magnam dicta.
            required:
                - id
        PackageDeletedEvent:
            type: object
            properties:
                id:
                    type: integer
                    description: Identifier of package
                    example: 4493684332048420724
                    format: int64
                item_deleted:
                    $ref: '#/components/schemas/Item'
            example:
                id: 6339936517794195207
                item_deleted:
                    description: Magnam dicta.
            required:
                - id
        PackageUpdatedEvent:
            type: object
            properties:
                id:
                    type: integer
                    description: Identifier of package
                    example: 6856838199796673538
                    format: int64
                item:
                    $ref: '#/components/schemas/Item'
            example:
                id: 6262640300446987135
                item:
                    description: Magnam dicta.
            required:
                - id
    securitySchemes:
        basic_header_Authorization:
            type: http
            description: Secures the login endpoint.
            scheme: basic
        jwt_header_Authorization:
            type: http
            description: Secures endpoint by requiring a valid JWT token. Supports scopes "stream:read" and "stream:write".
            scheme: bearer
tags:
    - name: chatter
      description: The chatter service implements a simple client and server chat.
